const SET_USER_TOKEN = 'SET_USER_TOKEN';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_USER_DETAIL = 'SET_USER_DETAIL';
const SET_LOADING = 'SET_LOADING';

export {SET_USER_TOKEN, SET_USER_DATA, SET_USER_DETAIL, SET_LOADING};
