const SET_LOADING = 'SET_LOADING';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_USER_DETAIL = 'SET_USER_DETAIL';
const SET_FOCUSED_SCREEN = 'SET_FOCUSED_SCREEN';

export {SET_LOADING, SET_USER_DATA, SET_USER_DETAIL, SET_FOCUSED_SCREEN};
